### ISSUE TITLE
notice.log is not generated in the current folder

### ISSUE THREAD

**Issue by likelyy** [seclab-ucr/Themis#1]
Thank you for answering my quesetion. I follew your step in **Usage**
3. To see how Robust Zeek can detect evasion attacks, we have pre-recorded attack traffic under pcaps/ folder. detect-bad-keywords.bro is a rule file to detect the sensitive keyword in a HTTP request.
```
zeek -r <pcap file>  effectiveness/detect-bad-keywords.bro -R
(A notice.log file will be generated in the current folder if the keyword is detected.)
```
I use pcap file in pcaps/ folder. However, I only see weird.log in the current folder. notice.log is not generated.
Are there any other settings I need to do? Thanks!

**Comment by gkso** [comment]
I found out that the problem is caused by my commenting out the code that registers the HTTP Analyzer. I forgot the reason why I did that. :(
But anyway I fixed the problem at @https://github.com/seclab-ucr/Themis/commit/3f966f81e90d3f3548c111b831d65d5d3c369aed
Thanks for reporting the issue!
